export interface Job {
  apply_options: object | null;
  employer_logo: string;
  employer_name: string;
  employer_website: string;
  job_apply_is_direct: boolean;
  job_apply_link: string;
  job_benefits: string | null;
  job_city: string | null;
  job_country: string;
  job_description: string;
  job_employment_type: string;
  job_employment_types: string[];
  job_google_link: string;
  job_highlights: object | null;
  job_id: string;
  job_is_remote: boolean;
  job_latitude: number;
  job_location: string;
  job_longitude: number;
  job_max_salary: number | null;
  job_min_salary: number | null;
  job_onet_job_zone: string;
  job_onet_soc: string;
  job_posted_at: string;
  job_posted_at_datetime_utc: string;
  job_posted_at_timestamp: number;
  job_publisher: string;
  job_required_skills: string | null;
  job_salary: number | null;
  job_salary_period: string | null;
  job_state: string | null;
  job_title: string;
}
