import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const genAi = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

export async function POST(req: NextRequest) {
  const body = await req.json();
  const query = body.query;

  if (!query) {
    return NextResponse.json(
      { error: "Missing query parameter" },
      { status: 400 }
    );
  }

  try {
    const response = await genAi.models.generateContent({
      model: "gemini-1.5-flash",
      contents: `Analyze the following text and return only the most relevant and suitable keywords. Do not provide any explanation or additional text. Only return a suitable job role for the given text: ${query}`,
    });

    if (!response.text) {
      return NextResponse.json(
        { message: "No response generated by Gemini API." },
        { status: 500 }
      );
    }

    const data = response.text;
    return NextResponse.json(data);
  } catch (error) {
    console.log(error);

    return NextResponse.json(
      {
        message: "An error occurred while processing your request.",
      },
      { status: 500 }
    );
  }
}
